services:
  frontend:
    image: front:v2
    container_name: fftfront
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=0.0.0.0
      - REACT_APP_API_PORT=80
    networks:
      - fftNet
    stdin_open: true

    volumes:
      - ./frontend:/app

  backend:
    image: back:v2
    container_name: fftback
    ports:
      - 80:80
    networks:
      - fftNet
    volumes:
      - ./app:/app

networks:
  fftNet:
    driver: bridge
